export const CurrencyOptions = [
  { label: "Euro", value: "EUR" },
  { label: "US Dollar", value: "USD" },
  { label: "British Pound", value: "GBP" },
  { label: "Swiss Franc", value: "CHF" },
  { label: "Japanese Yen", value: "JPY" },
  { label: "Canadian Dollar", value: "CAD" },
  { label: "Australian Dollar", value: "AUD" },
  { label: "Chinese Yuan", value: "CNY" },
  { label: "Polish Złoty", value: "PLN" },
  { label: "Czech Koruna", value: "CZK" },
  { label: "Hungarian Forint", value: "HUF" },
  { label: "Romanian Leu", value: "RON" },
  { label: "Bulgarian Lev", value: "BGN" },
  { label: "Swedish Krona", value: "SEK" },
  { label: "Danish Krone", value: "DKK" },
  { label: "Norwegian Krone", value: "NOK" },
  { label: "Icelandic Króna", value: "ISK" },
  { label: "Croatian Kuna", value: "HRK" },
  { label: "Turkish Lira", value: "TRY" },
  { label: "Indian Rupee", value: "INR" },
  { label: "Brazilian Real", value: "BRL" },
  { label: "South African Rand", value: "ZAR" },
  { label: "Mexican Peso", value: "MXN" },
];
