export const ApiRoutes = {
  auth: {
    email: {
      login: "/auth/email/login",
      register: "/auth/email/register",
      change_password: "/auth/email/change-password",
      refresh_token: "/auth/email/refresh-token",
      admin_login_to_account: (account_uuid: string) => `/auth/email/${account_uuid}/admin-login`,
      forgot_password: "/auth/forgot-password",
      reset_password: "/auth/reset-password",
      verify_email: "/auth/verify-email",
      resend_verification_email: "/auth/resend-verification-email",
    },
  },
  users: {
    prefix: "/users",
    me: "/users/me",
    user: (user_uuid: string) => `/users/${user_uuid}`,
  },
  routine: {
    activities: {
      list: "/activities",
      create: "/activities",
      get: (uuid: string) => `/activities/${uuid}`,
      update: (uuid: string) => `/activities/${uuid}`,
      delete: (uuid: string) => `/activities/${uuid}`,
    },
    scheduleSlots: {
      list: "/schedule-slots",
      create: "/schedule-slots",
      byDay: (day: string) => `/schedule-slots/by-day/${day}`,
      get: (uuid: string) => `/schedule-slots/${uuid}`,
      update: (uuid: string) => `/schedule-slots/${uuid}`,
      delete: (uuid: string) => `/schedule-slots/${uuid}`,
      duplicateDay: "/schedule-slots/duplicate-day",
      duplicateSlot: "/schedule-slots/duplicate-slot",
    },
  },
  fitness: {
    muscleGroups: {
      list: "/muscle-groups",
      create: "/muscle-groups",
      get: (uuid: string) => `/muscle-groups/${uuid}`,
      update: (uuid: string) => `/muscle-groups/${uuid}`,
      delete: (uuid: string) => `/muscle-groups/${uuid}`,
    },
    exercises: {
      list: "/exercises",
      create: "/exercises",
      get: (uuid: string) => `/exercises/${uuid}`,
      update: (uuid: string) => `/exercises/${uuid}`,
      delete: (uuid: string) => `/exercises/${uuid}`,
    },
    workouts: {
      list: "/workouts",
      create: "/workouts",
      get: (uuid: string) => `/workouts/${uuid}`,
      update: (uuid: string) => `/workouts/${uuid}`,
      delete: (uuid: string) => `/workouts/${uuid}`,
    },
    workoutEntries: {
      list: "/workout-entries",
      create: "/workout-entries",
      get: (uuid: string) => `/workout-entries/${uuid}`,
      update: (uuid: string) => `/workout-entries/${uuid}`,
      delete: (uuid: string) => `/workout-entries/${uuid}`,
      analytics: {
        progress: "/workout-entries/analytics/progress",
      },
    },
    workoutSets: {
      list: "/workout-sets",
      create: "/workout-sets",
      get: (uuid: string) => `/workout-sets/${uuid}`,
      update: (uuid: string) => `/workout-sets/${uuid}`,
      delete: (uuid: string) => `/workout-sets/${uuid}`,
    },
  },
  expenses: {
    accounts: {
      list: "/expense-accounts",
      create: "/expense-accounts",
      get: (uuid: string) => `/expense-accounts/${uuid}`,
      update: (uuid: string) => `/expense-accounts/${uuid}`,
      delete: (uuid: string) => `/expense-accounts/${uuid}`,
    },
    categories: {
      list: "/expense-categories",
      create: "/expense-categories",
      get: (uuid: string) => `/expense-categories/${uuid}`,
      update: (uuid: string) => `/expense-categories/${uuid}`,
      delete: (uuid: string) => `/expense-categories/${uuid}`,
    },
    subcategories: {
      list: "/expense-subcategories",
      create: "/expense-subcategories",
      get: (uuid: string) => `/expense-subcategories/${uuid}`,
      update: (uuid: string) => `/expense-subcategories/${uuid}`,
      delete: (uuid: string) => `/expense-subcategories/${uuid}`,
    },
    entries: {
      list: "/expense-entries",
      create: "/expense-entries",
      get: (uuid: string) => `/expense-entries/${uuid}`,
      update: (uuid: string) => `/expense-entries/${uuid}`,
      delete: (uuid: string) => `/expense-entries/${uuid}`,
      analytics: {
        balanceTrend: "/expense-entries/analytics/balance-trend",
        incomeExpense: "/expense-entries/analytics/income-expense",
        stats: "/expense-entries/analytics/stats",
        expensesBySubcategory: "/expense-entries/analytics/expenses-by-subcategory",
        transactionTrend: "/expense-entries/analytics/transaction-trend",
      },
    },
  },
}