export default () => ({
    NODE_ENV: process.env.NODE_ENV,
    PORT: Number(process.env.PORT),
    APP_URL: process.env.APP_URL,
    LANDING_URL: process.env.LANDING_URL,
    API_URL: process.env.API_URL,
    DATABASE_URL: process.env.DATABASE_URL,
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_EXPIRATION_TIME: process.env.JWT_EXPIRATION_TIME,
    GCS_PROJECT_ID: process.env.GCS_PROJECT_ID,
    GCS_BUCKET_NAME: process.env.GCS_BUCKET_NAME,
    GCS_FOLDER_NAME: process.env.GCS_FOLDER_NAME,
    GCS_CREDENTIALS_PATH: process.env.GCS_CREDENTIALS_PATH,
    GCS_CREDENTIALS: process.env.GCS_CREDENTIALS,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
});